language: node_js
node_js:
  - 'stable'
install:
  - yarn
stages:
  - type checking
  - unit testing
  - name: deploy docs
    if: branch = master
  - name: publish
    if: branch = master
jobs:
  include:
    - stage: type checking
      script: yarn tsc
    - stage: unit testing
      script: yarn test
    - stage: deploy docs
      script: yarn docz:build
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: .docz/dist
          on:
            branch: master
    - stage: publish
      before_deploy: cd pkg
      deploy:
        - provider: npm
          skip-cleanup: true
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          on:
          branch: master
